Add weather API, refactor CSS
berenteb/bkk-nearby-departures pull request #35
Opened 2021-04-04 16:05 UTC by KostyalBalint

**Design:** 
- Rewrite css colors, to use variables
- Create glassmorphism design for the tiles

**Weather data**
- Show background based on the current weather
- Show current temperature in the titlebar
- Weather info based on the lat and long coordinates

2021-04-04 18:13 UTC, berenteb commented on client/style.css
> +
This is a bit messy. I suggest using a specific class name for this.

2021-04-04 18:14 UTC, berenteb commented on client/style.css
Add z-index for the titleBar, it is overlapped for me.

2021-04-04 18:27 UTC, berenteb requested changes
The new feature looks nice and handful. Here are some recommendations and change requests, I will commit a fix for these:
- Add z-index for the titleBar, see comment
- Add class for those weather selectors, those selectors look complicated and not universal. Once the hierarchy is changed, the selector will break.
- °C instead of C°
- Round temperature, decimals are unuseful, and move the temperature field next to the settings button. It is an additional information, it doesn't have to be in the middle.
- Set the text color of the logo, or add a background to the titleBar.
- What happened to the margin of the titleBar?
- Minimalist illustrations instead of real photos? Maybe from Schdesign?

Overall, the glossy theme looks elegant. We'll need to compare the old style and the new style on the display. Also, I would suggest a checkbox for toggling the weather based background. Some might prefer the plain background.

2021-04-05 08:33 UTC, KostyalBalint commented on client/style.css
> +
I agree the nested classes are messy, we can replace it with a selector like this: .weather .field (notice the space between)
This will select every layer of nesting: https://css-tricks.com/child-and-sibling-selectors/
Also I would keep this .weather approach, because this way we can easily toggle the weather look from the plan look, just by adding a simple weather class to the body.

2021-04-05 08:34 UTC, KostyalBalint commented on client/style.css
It could be a problem yes, I only tested in chrome, I'll check.

2021-04-05 12:06 UTC, berenteb approved these changes

2021-04-05 13:02 UTC, berenteb commented
Will merge after error handling is solved!

2021-04-05 13:02 UTC, berenteb requested changes
Add error handling, write --°C if data is unavailable!

2021-04-05 13:47 UTC, berenteb approved these changes

2021-04-05 13:48 UTC, merged